apiVersion: v1
kind: ServiceAccount
metadata:
  name: dsaf-app-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dsaf-app-minimal-role
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dsaf-app-minimal-binding
subjects:
  - kind: ServiceAccount
    name: dsaf-app-sa
roleRef:
  kind: Role
  name: dsaf-app-minimal-role
  apiGroup: rbac.authorization.k8s.io